post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Enable optimization for Release builds
      if config.name == 'Release'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 's'
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['STRIP_STYLE'] = 'all'
        config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'YES'
        config.build_settings['DEPLOYMENT_POSTPROCESSING'] = 'YES'
        config.build_settings['SEPARATE_STRIP'] = 'YES'
      end
      
      # Ensure pods support minimum iOS version
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
